version: '2'

services:
  tomcat:
    image: vulhub/tomcat:8.0
    container_name: tomcat-lab
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./context.xml:/usr/local/tomcat/webapps/host-manager/META-INF/context.xml
    networks:
      - labnet

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24   # same subnet style as your example
