version: '2'

services:
  weblogic:
    image: vulhub/weblogic:10.3.6.0-2017
    container_name: weblogic-lab
    ports:
      - "7001:7001"
      - "5556:5556"
    volumes:
      - ./web:/root/Oracle/Middleware/user_projects/domains/base_domain/autodeploy
    networks:
      - labnet

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24   # same subnet style as your example
